### ISSUE TITLE
Example for working with Twilio for streaming?

### ISSUE THREAD

**Issue by cmaycumber** [deepgram/deepgram-node-sdk#103]
## Proposed changes

> There's currently a python and a rust version it'd be nice if we could see a Node version. 

## Context

> It would help me easily determine how to work with Twilio live transcriptions.

**Comment by briancbarrow** [comment]
@cmaycumber Thanks for opening this issue. We've added a task to our backlog to get an example working with Node and Twilio.

**Comment by vinny-888** [comment]
I made a working example using Twillio and DeepGram with node here: 

- https://github.com/vinny-888/twilio-media-stream-live-transcription-node

![image](https://github.com/deepgram/deepgram-node-sdk/assets/94944578/e8db91c3-89d9-4849-aab9-5e5d8ece9260)

I get the first utterance but the connection to DeepGram drops right after the first utterance for some reason.

**Comment by jpvajda** [comment]
@cmaycumber does the example @vinny-888  help you at all?
