### ISSUE TITLE
Keywords feature not working

### ISSUE THREAD

**Issue by SandraRodgers** [deepgram/deepgram-node-sdk#114]
## What is the current behavior?

I don't think the SDK is correct for how to make the keywords feature work. When I send an array of strings like the SDK docs say to do, those keywords don't improve. When I make the same request in CURL, they do improve. I think [this](https://github.com/deepgram/deepgram-node-sdk/blob/3c617e1381fef2483999e5f2eeadc4325bff8b56/src/types/usageOptions.ts#L15) is incorrect

## Steps to reproduce

Use the attached audio file CallCenterPhoneCall.mp3. Use this request:

```js
deepgram.transcription
  .preRecorded(
    {
      buffer: fileBuffer,
      mimetype: "mp3",
    },
    {
      punctuate: true,
      utterances: true,
      keywords: ["Charlie"],
    }
  )
```

Compare to CURL:

```
curl \                                 
  --request POST \
  --url 'https://api.deepgram.com/v1/listen?diarize=true&punctuate=true&utterances=true&keywords=charlie' \
 --header "Authorization: Token ${DGAPI}" \
  --header 'content-type: audio/mp3' \
 --data-binary @CallCenterPhoneCall.mp3 | jq -r '.results.utterances[] | "[Speaker:\(.speaker)] \(.transcript)"'
```

## Expected behavior

> What would you expect to happen when following the steps above?

When the speaker says his name, it should change to "Charlie" from "Shirley"

```
[Speaker:0] Okay. What is your name, sir?
[Speaker:1] Charlie Johnson.
```

**Comment by lukeocodes** [comment]
As far as I'm aware we should be unfurling the array of strings into multiple URL params.

```
    {
      keywords: ["Charlie", "Johnson"],
    }
```

Should result in.

```
&keywords=Charlie&keywords=Johnson
```

I'll look at this this week

**Comment by EylonSho** [comment]
Not working for me either. Additionally, how can I define the intensifier parameter there?

**Comment by wheel1992** [comment]
> Not working for me either. Additionally, how can I define the intensifier parameter there?

Hi @lukeocodes any luck on your findings?

I have tried to add intensifier for each keywords, but not working.

For example

```js
const options = {..., keywords: ["hello:-10", "yeah:-10"] }
```
