### ISSUE TITLE
Please make this available as an ESM build

### ISSUE THREAD

**Issue by benwoodward** [deepgram/deepgram-node-sdk#137]
## Proposed changes

Currently this is a CommonJS package

## Context

Really struggling to get my SvelteKit project to build with this package installed. SvelteKit uses Vite and is therefore works with ES modules only. There are some workarounds to get CommonJS packages working, but so far none of them are working for me.

```
#13 13.21 import { Deepgram } from "@deepgram/sdk";
﻿#13 13.21          ^^^^^^^^
﻿#13 13.21 SyntaxError: Named export 'Deepgram' not found. The requested module '@deepgram/sdk' is a CommonJS module, which may not support all module.exports as named exports.
﻿#13 13.21 CommonJS modules can always be imported via the default export, for example using:
﻿#13 13.21
﻿#13 13.21 import pkg from '@deepgram/sdk';
﻿ 
﻿#13 13.21 const { Deepgram } = pkg;
```

EDIT: for the record using the following syntax resolved the build error:

```
import pkg from '@deepgram/sdk';
﻿ 
const { Deepgram } = pkg;
```

**Comment by lukeocodes** [comment]
Hey @benwoodward this is a good idea. I'm adding this to our backlog to switch over to ESM for our next major version bump. Thanks for your feedback! I'll leave this open in the meantime

**Comment by cameronk** [comment]
Related to this: when using this in a Next.JS application (next.js 13, app directory) I receive this warning:

```
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../node_modules/@deepgram/sdk/dist/index.js
./src/lib/clients/deepgram.ts
...
```

My client code is standard:

```
import { Deepgram } from "@deepgram/sdk";
export const deepgram = new Deepgram(DEEPGRAM_API_KEY);
```

Believe this may be related.

**Comment by benwoodward** [comment]
I am not exposing my key in frontend code, no. I run Deepgram from a background job on a secure server.

**Comment by cameronk** [comment]
+1, this occurs when using Deepgram's SDK in a Next.js 13 route handler.

**Comment by wesbos** [comment]
Same issue with Sveltekit on Vercel. Plesae publish as a ESM module

**Comment by lukeocodes** [comment]
> Same issue with Sveltekit on Vercel. Plesae publish as a ESM module

We have an isomorphic version of the SDK currently in development. @wesbos I'd love to get some feedback on the approach (heavily inspired by supabase's JavaScript SDK). My hope is that we'll have an ESM, deno friendly, node friendly, Node SDK.

**Comment by TomFrankly** [comment]
+1 to this; I'd like to implement Deepgram's SDK in Pipedream steps, but they don't allow for a mix of CommonJS and EST modules in the same step.

**Comment by lukeocodes** [comment]
Hi @TomFrankly and everyone we have an unstable alpha now available on NPM. It includes an ESM build. The README is far behind the code (sadly), but there are opportunities to help us document it

https://www.npmjs.com/package/@deepgram/sdk?activeTab=versions
