### ISSUE TITLE
Errors thrown as strings

### ISSUE THREAD

**Issue by lox** [deepgram/deepgram-node-sdk#151]
## What is the current behavior?

We are getting errors out of the Deepgram sdk (specifically the preRecorded transcription calls) as strings. Should they not be objects?

Look like:
> DG: {"err_code":"Bad Request","err_msg":"Bad Request: failed to process audio: corrupt or unsupported data","request_id":"xxxxxxxxx"}

> What's happening that seems wrong?

There is no way to get the properties out (like request_id) without string parsing.

**Comment by lukeocodes** [comment]
Hey, thanks for raising this. It's a known issue, one that I'm keen to resolve as soon as possible.

There have been some past shifts in how the API has returned errors, and that work in on-going. We have #148 open which is tracking work to return errors as objects, among other improvements for V3 of the SDK. I'll keep this issue open and keep you updated as we work on this.

**Comment by lox** [comment]
Other thing I've encountered here is there doesn't seem to be a way to get a requestId from a failed transcription.
