### ISSUE TITLE
move bufferutil and utf-8-validate dependencies to optional 

### ISSUE THREAD

**Issue by RobZuazua** [deepgram/deepgram-node-sdk#157]
## Proposed changes

Can you remove bufferutil and utf-8-validate as dependencies and instead put as optional dependencies?

This will allow me to run "npm install --no-optional" when building my lambda.

Caveat:
- have to test that this is ok. 
- these packages are optional dependencies of ws, so not sure if y'all really need the hard dependency. if ur using them, then you can close this.

## Context

AWS Lambda runs on Amazon Linux, and some node packages with native extensions like bufferutil need to be compiled specifically for Amazon Linux.

## Possible Implementation

move bufferutil to optional dependency in package.json

**Comment by lukeocodes** [comment]
PRs welcome :)

**Comment by lukeocodes** [comment]
We've a new major version being released to beta this week, which no longer include these dependencies. We'd love to get your feedback on whether it resolves this issue. The latest alpha is stable enough to confirm this, or you can wait for the beta.
