### ISSUE TITLE
 JavaScript SDK for Browser Client

### ISSUE THREAD

**Issue by designcomputer** [deepgram/deepgram-node-sdk#161]
I've noted that a forthcoming JavaScript SDK has been mentioned in the past issues a number of times. 
Is there any update on this? 

The documentation still points people toward browser support that is no longer in the SDK.
[https://developers.deepgram.com/docs/node-sdk#browser](https://developers.deepgram.com/docs/node-sdk#browser)

_"As of version 2.x, the JS Browser SDK was removed from the Node SDK and will become an independent Client SDK. To use the older SDK, please npm i @deepgram/sdk@1.2.1 and use @deepgram/sdk/browser."_

This simple sample code is helpful. Do you have any more examples like this for streaming?
[https://deepgram.com/learn/live-transcription-mic-browser](https://deepgram.com/learn/live-transcription-mic-browser)

I understand the issue with exposing the API key on the client, but for our current project that isn't a problem.

**Comment by dandonahoe** [comment]
Same Question, I'm wondering which documentation is accurate.

**Comment by ulion** [comment]
same, wondering how to auth the websocket in browser.

**Comment by lukeocodes** [comment]
hey folks, our `next` SDK major rework is now in alpha. This is not considered stable, and the README is constantly being worked on. If you choose to check it out, we'd appreciate feedback in either standalone issues OR replies here (I genuinely don't mind, feedback is feedback).

https://www.npmjs.com/package/@deepgram/sdk?activeTab=versions

**Comment by lukeocodes** [comment]
#185 is being released to beta this week

it supports browser use, although not for REST calls (that is a CORs related limitation of our API). REST includes all our management API, and our pre-recorded transcriptions. You'll still be able to do "live transcription" in the browser.

It does natively support a proxy in the SDK, so you can use the SDK in the browser and proxy your requests to our REST endpoints. You can also use this proxy to introduce your API key into the headers, so you don't need to provide that in the client.

Looking forward to any feedback you might have.
