### ISSUE TITLE
Add discord badge to the top of the README

### ISSUE THREAD

**Issue by lukeocodes** [deepgram/deepgram-node-sdk#162]
Add a discord shield/badge to the top of the repo's README, linked to our community Discord (https://discord.gg/xWRaCDBtW4).

Name: Node SDK

![image](https://github.com/deepgram/deepgram-node-sdk/assets/956290/37117eff-e8d0-436d-a65b-2ad7259c79eb)

**Comment by subhajit20** [comment]
@lukeocodes hey want to help.
Can you assign it to me?

**Comment by jpvajda** [comment]
@subhajit20 Sure thing. Thanks for helping out!
