### ISSUE TITLE
Model fails for Songs

### ISSUE THREAD

**Issue by btahir** [deepgram/deepgram-node-sdk#168]
Not sure where to open this issue since its related to the model (nova-2-ea) itself.

Anyways - for some reason if you try to transcribe any audio (pre-recorded) with music it only transcribes the first few words. Not sure why this is happening and if its related to the music or the pauses? 

Appreciate any explanation and/or way to handle this.

**Comment by lukeocodes** [comment]
Hi @btahir for issues related to the service, could you please raise a question on [community forum](https://dpgr.am/community) or [Discord](https://dpgr.am/discord).
