### ISSUE TITLE
ALPHA: change examples on README for the new v3-alpha

### ISSUE THREAD

**Issue by lukeocodes** [deepgram/deepgram-node-sdk#169]
v3 alpha is now released: https://www.npmjs.com/package/@deepgram/sdk?activeTab=versions

If you're interested in helping us bring this release out faster, we require the README to stay up to date with changes we're still making in alpha.

Requirements:
- Fork this repo ❗ 
- Make a branch FROM the alpha branch ❗ 
- Review the tests, and the client format, to see the new usage ❗ 
- Update README for new usage examples
- Make a PR from your new branch, to the alpha branch ❗

**Comment by theavitw** [comment]
Should I try it out?

**Comment by sanchitaa14** [comment]
Can I help?

**Comment by lukeocodes** [comment]
@theavitw if you're still interested, and as you were first, I have assigned this to you.  Please let me know if you need any advice. You can reach out to me "lukeocodes" in both the Hacktoberfest and Deepgram Discord servers.

**Comment by lukeocodes** [comment]
@namit343 you're up, as I haven't heard from @theavitw

**Comment by deeseeker** [comment]
I am interested

**Comment by deeseeker** [comment]
@lukeocodes I am interested in the project

**Comment by nehareddies** [comment]
Hello, Can you pls tell what we will have to do since I didn't understand?
I am probably interested in learning and working on it if the work's still open!
I am a pretty much of beginner, I have experience with python
