### ISSUE TITLE
Cloudflare worker compatibility issue with LiveClient

### ISSUE THREAD

**Issue by WilliamKeating** [deepgram/deepgram-node-sdk#197]
## What is the current behavior?

When using the v3 Deepgram SDK in a ClouldFlare worker, the LiveClient constructor creates a WebSocket with an invalid protocol when running `deepGram.listen.live({ model: 'nova' });`. This results in a "WebSocket Constructor: The protocol header token is invalid" error.

`[mf:err] SyntaxError: WebSocket Constructor: The protocol header token is invalid.
    at new LiveClient 
    at ListenClient.live 
    at Object.fetch 
    at async jsonError `

## Steps to reproduce

1. Call `deepGram.listen.live({ model: 'nova' })` in ClouldFlare worker with Node.
2. Observe the "WebSocket Constructor: The protocol header token is invalid" error.

## Expected behavior

Not produce error

## Please tell us about your environment

  
- **Operating System/Version:** MacOS Ventura
- **Language:** TypeScript
- **Browser:** Node / ClouldFlare worker

**Comment by lukeocodes** [comment]
Thanks for letting me know. It seems the cloudflare worker makes the SDK think it's not a browser version of the websocket, and tried to define headers.

I'll look more at this today!

**Comment by lukeocodes** [comment]
This remains unresolved!

**Comment by lukeocodes** [comment]
fixed in v3.0.0-beta.4
