### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading '_req')

### ISSUE THREAD

**Issue by stevenou** [deepgram/deepgram-node-sdk#210]
## What is the current behavior?

Getting `TypeError: Cannot read properties of undefined (reading '_req')` after every session. It is received via the `LiveTranscriptionEvents.Error` listener. 

## Steps to reproduce

Honestly I don't know how to reproduce it but it seems to happen once at the end of every session. 

## Expected behavior

There shouldn't be any errors

## Please tell us about your environment
  
- **Operating System/Version:** Cloudflare Workers
- **Language:** JS
- **Browser:** N/A

## Other information

Using this config, if it matters:

```
deepgram.listen.live(
  {
    model: "nova-2-voicemail",
    punctuate: true,
    filler_words: false,
    alternatives: 1,
    numerals: true,
    endpointing: 10,
    sample_rate: 8000,
    encoding: "mulaw",
    channels: 1,
    interim_results: true,
    smart_format: true
  }
);
```

Everything works correctly (e.g. audio stream is sent successfully and transcript received correctly), except that this error is always received.

**Comment by lukeocodes** [comment]
Ahh my guess is that _req doesn't exist how you're using it. I think that might be one of a few lines that is from the V2 SDK :/

**Comment by stevenou** [comment]
confirmed fixed. thanks.
