### ISSUE TITLE
Channel type is missing language_confidence property

### ISSUE THREAD

**Issue by KaidenR** [deepgram/deepgram-node-sdk#212]
## What is the current behavior?

The "Channel" type has the "detected_language" property but is missing "language_confidence" as documented [here](https://developers.deepgram.com/docs/language-detection#analyze-response).

## Steps to reproduce

See Channel type:
https://github.com/deepgram/deepgram-node-sdk/blob/2734f695bfe574cd0bdfcd19227283bffae0acba/src/lib/types/SyncPrerecordedResponse.ts#L17

## Expected behavior

The Channel type should include the "language_confidence" property.

## Please tell us about your environment

N/A

## Other information

N/A

**Comment by lukeocodes** [comment]
Yikes! Thanks, we'll get this updated asap
