### ISSUE TITLE
Need to support the tags parameter in the /usage endpoint

### ISSUE THREAD

**Issue by MichaelJolley** [deepgram/deepgram-node-sdk#28]
## Proposed changes

Add the tags parameter to the /usage reporting endpoint

https://developers.deepgram.com/api-reference/#usage-summary

## Context

The API supports filtering summarized usage by tag, but the SDK doesn't support it.

**Comment by briancbarrow** [comment]
@MichaelJolley 

Doesn't this already support the tag?

Looking at the UsageOptions it looks to me like the tag is already in there.

https://github.com/deepgram/deepgram-node-sdk/blob/fbc58689bc2891ca4ae667ab7dc4baec72b3d6bf/src/types/usageOptions.ts#L5

**Comment by MichaelJolley** [comment]
Nope. Apparently, I didn't close this.
