### ISSUE TITLE
how to limit words count in each line of srt

### ISSUE THREAD

**Issue by wanghaisheng** [deepgram/deepgram-node-sdk#43]
```
1
00:00:00,299 --> 00:00:08,995
I mean before noon because my most productive time for me personally is between four and noon. And so I get all of my big tasks, especially my creative projects writing content

2
00:00:09,415 --> 00:00:23,360
for noon. Afternoon is what I reserved for talking to customers talking to employees team stuff because that's usually when I've i'm got in my creative do. I'm still one hundred percent functional for those types of meetings, but less so for extra abstract thoughts and, you know, putting things together. So for me, that's the optimal way to set up my day.


```
right now  i get only two line ,but i want them output like each line 25 characters at most
how can i limit word count

**Comment by MichaelJolley** [comment]
Hi @wanghaisheng, SRT segments are created from utterances from the API. You can adjust how aggressive the API breaks utterances by using the `utt_split` parameter in your request. It defaults to 0.8 seconds. Sending in a value less than that may possibly generate additional utterances and therefore generate additional lines in the SRT file.

**Comment by wanghaisheng** [comment]
that is helpful @MichaelJolley
