### ISSUE TITLE
Support for Enterprise Api (custom endpoints)

### ISSUE THREAD

**Issue by wodka** [deepgram/deepgram-node-sdk#45]
## Proposed changes
make the httpRequest more configureable. Like being able to pass in custom urls / switching between http and https.

## Context
right now there is no api client for enterprise. it would be nice to not only be able to use the types and query manually.

## Possible Implementation
one way would be to just provide configuration with a httpRequest interface that then just calls the sub path.

## Other information
no

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201885737791795/1202182488899707) by [Unito](https://www.unito.io)

**Comment by MichaelJolley** [comment]
I like the idea @wodka. Question: when you say "enterprise API," are you talking about on-premise installs vs hosted? We use the term "enterprise" to mean a specific API that's been deprecated as people move to the new "console" API.

**Comment by MichaelJolley** [comment]
@wodka, thanks for this feedback. The current versions of the SDK do support on-prem API deployments.
