### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by sircon** [deepgram/deepgram-node-sdk#55]
## What is the current behavior?
I'm trying to upgrade from `~1.3.1` to the latest package version `~1.4.5` and all the imports from this package are now throwing the following error:
```
File '.../node_modules/@deepgram/sdk/dist/index.d.ts' is not a module.ts(2306)
```

> What's happening that seems wrong?
Looking into the `index.d.ts` from both versions they're definitely different, and the version from `1.3` was exporting the `Deepgram` module and now it doesn't seem so.

## Steps to reproduce
1. Start a typescript project
2. Install the latest version from the SDK: `yarn add @deepgram/sdk@latest`;
3. Import the sdk `import { Deepgram } from '@deepgram/sdk';`
4. Typescript will give an error.

## Expected behavior
I'd expect to import not only the main `Deepgram` class, but also many other different types such as: `PrerecordedTranscriptionResponse`, `WordBase`, etc.

## Please tell us about your environment
- **Operating System/Version:** MacOS 11.5.2
- **Language:** TypeScript 4.7.4

## Other information
https://stackblitz.com/edit/typescript-vbkaj4?file=index.ts you might need a bit for it to fully load the linter but the result will be the same as the image:
![image](https://user-images.githubusercontent.com/1938296/182617347-0df3d4a5-356b-4af9-829b-2498b8d9a94a.png)

**Comment by MichaelJolley** [comment]
Amazing find and detail @sircon! We're on this now.

**Comment by MichaelJolley** [comment]
Thanks again for reporting this @sircon. Version 1.4.7 has just been released and should have resolved this. 

I tested in a StackBlitz that you can check out here: https://stackblitz.com/edit/typescript-g4e1dm?file=index.ts

**Comment by sircon** [comment]
Thanks for the fix @MichaelJolley but... although the `Deepgram` works now, there are some issues with other types. In version `1.3.1` I could import `PrerecordedTranscriptionResponse` and `WordBase` form your package and now it doesn't seem to find it anywhere. Looking at your `dist` folder, it looks like you are missing two important folders you had before `types/index.d.ts` and the `transcription/index.d.ts`.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/1938296/183032393-19b9684f-3db5-4e80-a9ef-97e1143406aa.png">

Do you think you can add these too?

**Comment by sircon** [comment]
For reference, how it looked before:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1938296/183033673-c063021e-2526-4f43-a47e-1e3e46ac3571.png">

I could just copy & paste the interfaces, but obviously having it always up to date with the package would be the ideal situation!

**Comment by MichaelJolley** [comment]
Ugh. Can't believe I missed that. 1.4.8 should have them restored.

**Comment by sircon** [comment]
Works great @MichaelJolley, thanks for the quick fixes!
