### ISSUE TITLE
Documentation - optional apiUrl in the Deepgram constructor

### ISSUE THREAD

**Issue by SandraRodgers** [deepgram/deepgram-node-sdk#75]
The SDK is set up so that the constructor accepts a required apiKey, but it can also take an optional apiUrl. 

```
constructor(apiKey: string, apiUrl?: string)
```

This could be added to the documentation.

**Comment by MichaelJolley** [comment]
Are you wanting it added to the actual documentation? If so, this should probably live in that repository.
