### ISSUE TITLE
Need some help for error DG: undefined: undefined

### ISSUE THREAD

**Issue by wuttichowcho** [deepgram/deepgram-node-sdk#77]
1. I try to convert some audio link (https://traffic.megaphone.fm/GLT8627189710.mp3?updated=1655947230) that I get from https://blog.deepgram.com/create-readable-transcripts-for-podcasts/?utm_source=youtube&utm_content=bPvt2JJMqvI

I use NodeJs for develop Deepgram. When I run the code for convert audio link, it throw error `DG: undefined: undefined`. I don't know what it means and how to fix it.

My code is here.

```

// Example filename: index.js

const fs = require('fs')
const { Deepgram } = require('@deepgram/sdk')

// Your Deepgram API Key
const deepgramApiKey = 'MY_API_KEY'

// Location of the file you want to transcribe. Should include filename and extension.
// Example of a local file: ../../Audio/life-moves-pretty-fast.wav
// Example of a remote file: https://static.deepgram.com/examples/interview_speech-analytics.wav
const file = 'https://traffic.megaphone.fm/GLT8627189710.mp3?updated=1655947230'

// Mimetype for the file you want to transcribe
// Only necessary if transcribing a local file
// Example: audio/wav
const mimetype = 'YOUR_FILE_MIME_TYPE'

// Initialize the Deepgram SDK
const deepgram = new Deepgram(deepgramApiKey)

// Check whether requested file is local or remote, and prepare accordingly
if (file.startsWith('http' || 'https')) {
  // File is remote
  // Set the source
  source = {
    url: file,
  }
} else {
  // File is local
  // Open the audio file
  const audio = fs.readFileSync(file)

  // Set the source
  source = {
    buffer: audio,
    mimetype: mimetype,
  }
}

// Send the audio to Deepgram and get the response
deepgram.transcription
  .preRecorded(source, {
    punctuate: true,
  })
  .then((response) => {
    // Write the response to the console
    console.dir(response, { depth: null })

    // Write only the transcript to the console
    console.log('\n\n\n\n\n\n')
    console.dir(response.results.channels[0].alternatives[0].transcript, { depth: null });
  })
  .catch((err) => {
    console.log('Error ==>', err)
  })
```

I think the error should contain error code or message describing something which what mistake point , so please help me investigate this what am I wrong and what is `DG: undefined: undefined`.

2. Anyway I need to convert podcast to transcribe so what kind of podcast link that suitable for use in Deepgram.

Thank you and best regard.

**Comment by MichaelJolley** [comment]
Hi @wuttichowcho, just confirming, did you change the line of code that reads `const deepgramApiKey = 'MY_API_KEY'` to contain your actual Deepgram API key?

**Comment by wuttichowcho** [comment]
@MichaelJolley Yes I have already change `MY_API_KEY` to my real API_KEY.

**Comment by BekahHW** [comment]
@wuttichowcho did you change the mimetype as well?

`const mimetype = 'YOUR_FILE_MIME_TYPE'`

**Comment by wuttichowcho** [comment]
@BekahHW I have not change because I need to transcribe with file's link, not local file.

**Comment by BekahHW** [comment]
@wuttichowcho it works on my end. 

Did you run `npm install @deepgram/sdk`?

And then run `node index.js`?

If you try that and it doesn't work, start a discussion in our [Community Discussion Q&A](https://github.com/orgs/deepgram/discussions/categories/q-a) and give the details of what you've done.

**Comment by MichaelJolley** [comment]
@wuttichowcho is your code in a public repo that we can check out? Everything seems to check out in our tests.

**Comment by JeffVega** [comment]
I followed the first and second approaches on this URL https://blog.deepgram.com/protecting-api-key/
I received the same error DG: undefined: undefined

**Comment by MichaelJolley** [comment]
This is quite puzzling. I copied @wuttichowcho's code above and pasted in my API key. The transcription was written back to my shell. I also tried the steps in the blog post mentioned by @JeffVega and they worked as well.

Can either of you let me know the version number of the SDK that's installed in your tests?

I copied @wuttichowcho's code above into a [Glitch](https://glitch.com/edit/#!/three-silent-lodge). Can you try to remix that Glitch and see if it works? You'll need to add your Deepgram API key to the `.env` file. It should write the transcription into the log as shown below.

![image](https://user-images.githubusercontent.com/1228996/196828449-b166f068-ff1e-4d26-a9f6-9c9ab703a996.png)

**Comment by wuttichowcho** [comment]
@MichaelJolley I installed sdk with "@deepgram/sdk": "^1.8.0",. Anyway I run my code (same code that I post in topic) again 2 times, It work now.

**Comment by MichaelJolley** [comment]
I wonder if there's an issue with that version. The latest is `1.10.1`.

**Comment by MichaelJolley** [comment]
I haven't been able to reproduce this with the latest version of the SDK. If it continues to occur, make sure you're using the latest version of the SDK. If you are, feel free to reopen this issue and give us some details.
