### ISSUE TITLE
Sample code snippet for live transcription located on the README file does not work.

### ISSUE THREAD

**Issue by baezor** [deepgram/deepgram-node-sdk#86]
Hi Deepgram team, excellent work with the SDK. I love it! 💯 

I found a minor issue on the README file. I copied and pasted the code snippet for live transcription on my project, but it didn't work. I believe it requires a few adjustments, which I propose in my pull request. #87 

**Fixed:**
- Replaced addListener for addEventListener because addListener does not exist on the browser.
- The `transcriptReceived` doesn't work for **@deepgram/sdk/browser**, I suggest using the `message` event listener.
- Lastly, on the message event listener, parse the `message` argument before. 

Hopefully, this helps to improve the documentation.

**Comment by briancbarrow** [comment]
closed with #87
