### ISSUE TITLE
Importing @deepgram/sdk/browser is throwing: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by Limeslices** [deepgram/deepgram-node-sdk#89]
## What is the current behavior?

>When trying to do the following
```
import { Deepgram } from '@deepgram/sdk/browser'
```

I run into this error
```
SyntaxError: Unexpected token 'export'
```

This is running on a NextJs localhost environment.

**Comment by IvanCoronado** [comment]
I have the same error. The browser version is not exported...

It looks like the doc is outdated.

**Comment by briancbarrow** [comment]
@Limeslices @IvanCoronado what version of the SDK were you using? Sorry for the late response. I had an example of this syntax working in v1.11.0 and still in v1.18.0. 

Let me know if you are still running into issues.

**Comment by lukeocodes** [comment]
Closing due to the age and no followups. Please use the latest version and raise a new issue if this continues to be a problem.
