### ISSUE TITLE
1.11.0 made times parameter required in PrerecordedTranscriptionOptions

### ISSUE THREAD

**Issue by kierandunbar** [deepgram/deepgram-node-sdk#92]
## What is the current behavior?

As of 1.11.0, a new `times` formatting parameter was introduced in `PrerecordedTranscriptionOptions` which is non-optional.
This broke our existing code on upgrade, and it doesn't look like it's referenced in any documentation.

## Steps to reproduce

Install 1.11.0 or above, `times` is now required.

## Expected behavior

`times` should be optional and default to whatever it did before (unsure whether this is true or false).
Ideally the documentation should reference it also (along with the other formatting options)

## Please tell us about your environment

N/A

## Other information

N/A

**Comment by ShantanuNair** [comment]
+1 Also noticed this just now.

**Comment by briancbarrow** [comment]
Thanks for pointing this out. Fixed this today in v1.18.0 with #110
